#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
  #source "~/.terraform_secrets"
fi
# export GOPATH=$HOME/go
# export PATH=$GOPATH/bin:$PATH
# export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"
