#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Useful file sizes in ls
alias ls="ls -h"

# alias rake="noglob rake"

fpath=(/usr/local/share/zsh-completions $fpath)

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export TF_VAR_infoblox_user=graham_gilbert
export TF_VAR_infoblox_password=PASSWORD
export TF_VAR_chef='{ user = "graham_gilbert", key = "~/chef-repo/.chef/graham_gilbert.pem" }'
export TF_VAR_aws_role=TF_ADMIN

export AWS_DEFAULT_REGION="us-east-1"

TF_VAR_region="us-east-1"; export TF_VAR_region
export GOPATH=$(go env GOPATH)
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:${HOME}/Library/Python/2.7/bin
export PATH=$PATH:${HOME}/.rbenv/bin

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/graham_gilbert/Dropbox (Personal)/Config/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/graham_gilbert/Dropbox (Personal)/Config/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/graham_gilbert/Dropbox (Personal)/Config/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/graham_gilbert/Dropbox (Personal)/Config/google-cloud-sdk/completion.zsh.inc'; fi


[ -d "/usr/local/Cellar/rbenv" ] && eval "$(rbenv init -)"
